### PR TITLE
Add support for defining event names in constructor.

### LINKED ISSUE #1: Event names as default constructor parameter(s)
Hi!

First of all, thanks for this nice, slick library!

I don't like it very much the way that you are forced to subsclass Events if you want to specify the event names. Would you take a pull request to accept an optional constructor parameter for the event names?

Thanks!

### PR DESCRIPTION
**Pull request by ajpen**
Resolves #1 

- Events that are initialized by a list/tuple of event names,
will have those names stored in __events__, local to that instance only.

- Both `__events__` and `__class__.__events__` will be evaluated, long as they
exist. 

It is not recommended to use both the constructor method and the `__events__` class variable simultaneously.

### CODE REVIEW

**Comment by ajpen** [comment]
I suppose I should update the documentation as well.

**Comment by nicolaiarocci** [comment]
Yes please
-- 
Nicola Iarocci
http://nicolaiarocci.com

**Comment by ajpen** [comment]
I'm not sure if we should embrace the use of both `__events__` and the constructor method simultaneously. Using them together can do really neat things like:

```
DatabaseEvents(Events):
    __events__ = ('insert', 'update', 'delete', 'select')

audit_events = ('select')

AppDatabaseEvents = DatabaseEvents()
AuditDatabaseEvents = DatabaseEvents(audit_events)
```

It can also have unexpected behavior, if one expects `AuditDatabaseEvents` to have insert events, because it is defined in `DatabaseEvents`.

What do you think?

**Comment by nicolaiarocci** [comment]
I think it is a nice feature to have, as long as we also add a note about it in the docs ;-)

**Comment by ajpen** [comment]
Sounds good. I'll add a test case for it in the suite and update the docs.

**Comment by ajpen** [comment]
Should be set now. Let me know if the docs are okay.

**Comment by nicolaiarocci** [comment]
Thanks!

**Comment by ajpen** [comment]
Sure. Happy to contribute!

**Pull request merged**
