### PR TITLE
Added __getitem__ dunder to Events class

### PR DESCRIPTION
**Pull request by CaileanMParker**
Added `__getitem__` dunder to Events class. This allows the calling of events from strings, thus enabling dynamic events. For instance:

```
events = Events(tuple(f"on_{i}" for i in range(5)))

for i in range(5):
    events[f"on_{i}"](i)
```

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Hi, this is a nice addition, thank you. Could you please add a test for it?

**Comment by CaileanMParker** [comment]
Many thanks, I'm glad you think so! And can do.

**Comment by CaileanMParker** [comment]
I just modified the existing test_getitem class, hope that's alright.

**Comment by nicolaiarocci** [comment]
thanks

**Pull request merged**
